---
- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable' state=present

- name: Install Nginx
  apt: pkg=nginx state=installed update_cache=true
  notify:
    - Start Nginx

- name: Add H5BP Config
  copy: src=h5bp dest=/etc/nginx owner=root group=root
  tags:
    - vhost

- name: Add Nginx Config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root
  tags:
    - vhost

- name: Add Nginx Mime Types
  copy: src=mime.types dest=/etc/nginx/mime.types owner=root group=root
  tags:
    - vhost

- name: Disable Default Site
  file: dest=/etc/nginx/sites-enabled/default state=absent
  tags:
    - vhost

- name: Add SFH Site Config (main or forums)
  template: src={{ domain }}.j2 dest=/etc/nginx/sites-available/{{ domain }}.conf owner=root group=root
  tags:
    - vhost
  notify:
    - Reload Nginx

- name: Enable SFH Site Config
  file: src=/etc/nginx/sites-available/{{ domain }}.conf dest=/etc/nginx/sites-enabled/{{ domain }}.conf state=link
  tags:
    - vhost
  notify:
    - Reload Nginx

#- name: Create Web root
#  when: nginxinstalled|success
#  file: dest=/var/www/{{ domain }}/public mode=775 state=directory owner=www-data group=www-data
#  ignore_errors: yes
#  notify:
#    - Reload Nginx

#- name: Web Root Permissions
#  when: nginxinstalled|success
#  file: dest=/var/www/{{ domain }} mode=775 state=directory owner=www-data group=www-data recurse=yes
#  ignore_errors: yes
#  notify:
#    - Reload Nginx